apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d
  template:
    metadata:
      labels:
        app: d
    spec:
      containers:
        - name: message-service
          image: mridul017/message-service-sender:latest
          env:
            - name: AMQP_SERVER_URL
              value: amqp://rabbitmq-server:5672
          ports:
            - containerPort: 3000
